name:                htrs
version:             0.1.0.0
github:              "akito19/htrs"
license:             BSD3
author:              "Akito Kasai"
maintainer:          "kasai@akito19.com"
copyright:           "2020 Akito Kasai"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/akito19/htrs#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- containers

library:
  source-dirs: src

executables:
  htrs:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - htrs

tests:
  htrs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - htrs
